set -e

die() {
  echo
  echo "*** $@" >&2
  exit 1
}


if [[ -d "../xslt-coverage" ]]; then

    echo "Running WITH code coverage. Remember to set SAXON_HOME and XSPEC_HOME"

    [[ -d ./coverage/ ]] || mkdir ./coverage/ || die "Could not create ./coverage/ directory"

    ../xslt-coverage/xslt-coverage.bash to-xslt.xsl ./recipe.xml ./coverage/coverage-one.json autogenerated.xsl
    ../xslt-coverage/xslt-coverage.bash autogenerated.xsl ./input.xhtml ./coverage/coverage-two.json output.xhtml

    node ../xslt-coverage/mergeCoverageFiles.js coverage/coverage-one.json coverage/coverage-two.json > coverage/coverage-final.json

else
    echo "********************************************************************"
    echo "Running without code coverage. To add code coverage, clone "
    echo "https://github.com/philschatz/xslt-coverage to a sibling directory (../xslt-coverage)" 
    echo "and follow its instructions."
    echo "********************************************************************"
    echo ""
    echo "Waiting for 10 seconds"
    sleep 10

    if [[ ! $(command -v saxon 2> /dev/null) ]]; then
        die "Could not find saxon XSLT transformer. Install it from https://saxonica.com"
    fi

    echo "Generating XSL"
    saxon -s:./recipe.xml -xsl:./to-xslt.xsl -o:./autogenerated.xsl 

    echo "Running Transform"
    saxon -s:./input.xhtml -xsl:./autogenerated.xsl -o:./output.xhtml 

fi