set -e

if [[ ! $(command -v saxon 2> /dev/null) ]]; then
    echo "Could not find saxon XSLT transformer. Install it from https://saxonica.com"
    exit 110
fi

echo "Generating XSL"
saxon -s:./recipe.xml -xsl:./to-xslt.xsl -o:./autogenerated.xsl 

echo "Running Transform"
saxon -s:./input.xhtml -xsl:./autogenerated.xsl -o:./output.xhtml 
