<!--
    Extract the book-specific class names of notes and create a book-specific Relax-NG schema file.
-->

<xsl:stylesheet
    xmlns="http://relaxng.org/ns/structure/1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:g="urn:recipe-config-xml"
    exclude-result-prefixes="g"
    version="1.0">

<xsl:output method="xml" indent="yes"/>

<xsl:template match="/">
    <xsl:comment>This file is autogenerated. DO NOT EDIT.</xsl:comment>
    <xsl:comment>Same as cnxml-common-jing.rng in the cnxml repo except that we load a different cnxml-defs.rng so that we can restrict the valid classes on features</xsl:comment>

    <!-- Boilerplate except for the xsl:for-each below -->
    <grammar ns="http://cnx.rice.edu/cnxml">

        <start>
            <choice>
            <ref name="document"/>
            </choice>
        </start>

        <include href="common-schema/cnxml-common-jing.rng"/>

        <define name="block-note">
            <element name="note">
                <attribute name="class">
                    <choice>
                        <xsl:for-each select="g:root/g:note">
                            <value>
                                <xsl:value-of select="@class"/>
                            </value>
                        </xsl:for-each>
                    </choice>
                </attribute>

                <xsl:comment>copied from cnxml-defs.rng but using common-attribute-noclass</xsl:comment>
                <ref name="display-block-default-attribute"/>
                <ref name="common-attributes-noclass"/>
                <ref name="id-attribute"/>
                <ref name="note-type-attribute"/>
                <optional>
                    <ref name="label"/>
                </optional>
                <ref name="div-content"/>
            </element>
        </define>
    </grammar>
</xsl:template>

</xsl:stylesheet>